#!/bin/bash

total=0
while read int;do
#for i in grep '"-"' log.txt | cut -d' ' -f1 | sort | uniq -c | sort -n | tail | tac | tr -s ' ' | cut -d' ' -f2; do
total=$((total + $int))
done< <(grep '"-"' log.txt | cut -d' ' -f1 | sort | uniq -c | sort -n | tail | tac | tr -s ' ' | cut -d' ' -f2)

i=1
while read num host; do
printf "$i. $host - $num - $(echo "scale=1; $num * 100 / $total" | bc)%%\n"
i=$((i + 1))
done < <(grep '"-"' log.txt | cut -d' ' -f1 | sort | uniq -c | sort -n | tail | tac | tr -s ' ' | cut -d' ' -f2,3)
